config/routes.rb
Rails.application.routes.draw do
  root to: 'homes#top'
  get 'home/about', to: 'homes#about'
  devise_for :users
  resources :books
  resources :users, only: [:index, :show, :edit, :update]
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/book.rb
class Book < ApplicationRecord
  has_one_attached :image
  belongs_to :user
  
  validates :title, presence: true
  validates :body, presence: true, length: { maximum: 200 }
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable


  has_many :books, dependent: :destroy
  has_one_attached :profile_image

  validates :name, uniqueness: true, length: { in: 2..20 }
  validates :introduction, length: { maximum: 50 }

  def get_profile_image(weight, height)
  unless profile_image.attached?
    file_path = Rails.root.join('app/assets/images/no_image.jpg')
    profile_image.attach(io: File.open(file_path), filename: 'default-image.jpg', content_type: 'image/jpeg')
  end
    profile_image.variant(resize_to_limit: [weight, height]).processed
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!, except: [:top, :about]
  before_action :configure_permitted_parameters, if: :devise_controller?

  def after_sign_in_path_for(resource)
    user_path(@user)
  end
  
  def after_sign_out_path_for(resource)
    root_path
  end

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name, :email])
  end
end

app/controllers/books_controller.rb
class BooksController < ApplicationController
  before_action :authenticate_user!
  before_action :correct_user, only: [:edit]


  def index
    @book = Book.new
    @books = Book.all
    @user = current_user
  end

  def new
    @book = Book.new
  end


  def create
    @book = Book.new(book_params)
    @book.user_id = current_user.id
    if @book.save
      flash[:notice] = "You have created book successfully."
      redirect_to @book
    else
      @user = current_user
      @books = Book.all
      @book_new = Book.new 
      render :index
    end
  end

  def show
    @book = Book.find(params[:id])
    @book_new = Book.new
    @user = @book.user
  end

  def edit
    @book = Book.find(params[:id])
  end

  def update
    @book = Book.find(params[:id])
    if @book.update(book_params)
      flash[:notice] = "You have updated book successfully.."
      redirect_to @book
    else
      render :edit
    end
  end

  def destroy
    @book = Book.find(params[:id])
    @book.destroy
    redirect_to @book
  end

  private
  def book_params
    params.require(:book).permit(:title, :body)
  end

  def correct_user
    @book = current_user.books.find_by(id: params[:id])
    redirect_to books_path if @book.nil?
  end

end

app/controllers/homes_controller.rb
class HomesController < ApplicationController
  def top
  end
  
  def about
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user!
  def index
    @book = Book.new
    @users = User.all
    @user = current_user
  end


  def show
    @user = User.find(params[:id])
    @books = @user.books
    @book_new = Book.new
    @user_books = @user.books
  end

  def edit
    user = User.find(params[:id])
    unless user.id == current_user.id
      redirect_to user_path(current_user)
    end
      @user = User.find(params[:id])
  end

  def update
    @user = User.find(params[:id])
    if @user.update(user_params)
     flash[:notice] = "You have updated user successfully."
     redirect_to user_path(@user)
    else
      render :edit
    end
  end

  private

  def user_params
    params.require(:user).permit(:name, :introduction, :profile_image)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/books/_user_info.html.erb
<div class="col-md-3">
  <h2>User info</h2>
  <% if user_signed_in? %>
  <%= image_tag user.get_profile_image(100,100) %>
  <table class="table">
    <thead>
      <tr>
        <th>name</th>
        <th><%= user.name %></th>
        <th colspan="2"></th>
      </tr>
    </thead>
             
    <tbody>
      <tr>
        <th>introduction</th>
        <th><%= user.introduction %></th>
      </tr>
      <% end %>
    </tbody>
    </table>
    
    <div class="row">
    <%= link_to edit_user_path(user), class: "btn btn-outline-secondary btn-block" do %>
      <i class="fas fa-user-cog"></i>
      <% end %>
    </div>
       
    <h2 class="mt-3">New book</h2>
    <%= form_with model: book do |f| %>
    <div class="form-group">
      <p>Title</p>
      <%= f.text_field :title, style: "width: 260px;" %>
      </div>
	    <p>Opinion</p>
      <%= f.text_area :body, style: "width: 260px;" %>
	
	    <div class="create">
      <%= f.submit 'Create Book', class: "btn btn-success" %>
      <% end %>
      </div>
    </div>

app/views/books/edit.html.erb
<main>
  <p id="notice"></p>
  <div class="container">
    <div class="row">
      <div class="col-sm-12 col-md-8 col-lg-5 px-5 px-sm-0 mx-auto">

        <h1>Editing Book</h1>
        <%= form_with model: @book do |f| %>
        
          <% if @book.errors.any? %>
          <div id="error_explanation">
            <h3><%= pluralize(@book.errors.count, "error") %> prohibited this obj from being saved:</h3>
            <ul>
              <% @book.errors.full_messages.each do |message| %>
            <li><%= message %></li>
              <% end %>
           </ul>
        </div>
        <% end %>
        
        
        <div class="form-group">
          <label for="inputName">Title</label><br>
        <%= f.text_field :title, style: "width: 480px;" %>
        </div>
        <div class="form-group">
          <label for="inputName">Opinion</label><br>
        <%= f.text_area :body, style: "width: 480px;" %>
  
        <div class="update"></div>
        <%= f.submit 'Update Book', class: "btn btn-success" %>
        <% end %>
  
        <div></div>
          <%= link_to 'Show', @book %> |
          <%= link_to 'Back', books_path %>
        </div>
      </div>
    </div>
  </div>
</main>

app/views/books/index.html.erb
<main>
  <p id="notice"></p>
    <div class="container px-5 px-sm-0" >
      
    <% if @book.errors.any? %>
    <div class="error_explanation">
      <h3><%= pluralize(@book.errors.count, "error") %> prohibited this obj from being saved:</h3>
      <ul>
        <% @book.errors.full_messages.each do |message| %>
        <li><%= message %></li>
        <% end %>
      </ul>
    </div>
    <% end %>

    <div class="row">
      <%= render "books/user_info", user: @user, book: @book %>

        <div class="col-md-8 offset-md-1">
          <h2>Books</h2>
          <table class="table table-hover">
            <thead>
              <tr>
                <th></th>
                <th>Title</th>
                <th>Option</th>
                <th colspan="3"></th>
              </tr>
            </thead>
            <tbody>
              <% @books.each do |book| %>
            <tr>
              <td><%= link_to image_tag(book.user.get_profile_image(100,100)), user_path(book.user) %></td>
              <td><%= link_to book.title, book_path(book) %></td>
              <td><%= book.body %></td>
            </tr>
              <% end %>
            </tbody>
        </table>
      </div>
    </div>
  </div>
</main>

app/views/books/new.html.erb
<h1>Books#new</h1>
<p>Find me in app/views/books/new.html.erb</p>

app/views/books/show.html.erb
<main>
  <p id="notice"></p>
  <div class="container px-5 px-sm-0" >
    <div class="row"> 
      <%= render "books/user_info", user: @user, book: @book_new %>
        
        <div class="col-md-8 offset-md-1">
        <h2>Book detail</h2>
        <table class="table">
          <tbody>
            <tr>
              <td>
                <%= link_to image_tag(@user.get_profile_image(100,100)), user_path(@user) %><br>
                <%= link_to @user.name, user_path(@user) %>
              </td>
              <td><%= link_to @book.title, book_path(@book) %></td>
              <td><%= @book.body %></td>
              <% if @book.user == current_user %>
              <td><%= link_to 'Edit', edit_book_path(@book), class: "btn btn-success"  %></td>
              <td><%= link_to 'Destroy', book_path(@book), class: "btn btn-danger", method: :delete, data: { confirm: '本当に消しますか？' } %></td>
              <% end %>
            </tr>
          </tbody>
        </table>
      </div>
    </div>
  </div>
</main>

app/views/homes/about.html.erb
<main>
  <p id="notice"></p>
  <div class="container">
    <div class="row">
      <div class="mx-auto">
        <h1>Welcome to <i class="fas fa-book"></i><strong>Bookers</strong>!</h1>
      </div>
    </div>
  </div>
</main>

app/views/homes/top.html.erb
<main>
  <p id="notice"></p>
  <div class="container">
    <div class="row">
      <div class="mx-auto col-11 col-sm-10 col-lg-8 col-xl-6">
        <h1>welcome to <i class="fas fa-book"></i><strong>Bookers</strong>  !!</h1>
        <p>In  <i class="fas fa-book"></i><strong>Bookers</strong>, </p>
        <p>you can share and exchange your opinions , inpressions , and emotions</p>
        <p>about various books!</p>
        <div class="btn-wrapper col-10 mx-auto">
          <div class="row">
            <a class="btn btn-info btn-sm btn-block mb-3" href="/users/sign_in" style="width: 800px;">Log in</a>
          </div>
          <div class="row">
            <a class="btn btn-success btom-sm btm-brock" href="/users/sign_up" style="width: 800px;">Sign up</a>
          </div>
        </div>
      </div>
    </div>
  </div>
</main>
 

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Bookers2</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_pack_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

<body>
  <header>
    <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
      <div class="container">
      <a class="navbar-brand" href="/">
        <span>Bookers</span>
      </a>
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarNavDropdown">
        <ul class="navbar-nav ml-auto">
          <% if user_signed_in? %>
          <li class="nav-item">
            <%= link_to current_user, class: 'nav-link text-light' do %>
          <i class="fas fa-home"></i> Home
            <% end %>
          </li>
          <li class="nav-item">
            <%= link_to users_path, class: 'nav-link text-light' do %>
          <i class="fas fa-users"></i> Users
            <% end %>
          </li>
          <li class="nav-item">
            <%= link_to books_path, class: 'nav-link text-light' do %>
          <i class="fas fa-book-open"></i> Books
            <% end %>
          </li>
          <li class="nav-item">
            <%= link_to destroy_user_session_path, method: :delete, class: 'nav-link text-light' do %>
          <i class="fas fa-sign-out-alt"></i> Log out
            <% end %>
          </li>
          <% else %>
          <li class="nav-item">
            <%= link_to root_path, class: 'nav-link text-light' do %>
              <i class="fas fa-home"></i> Home
            <% end %>
          </li>
          <li class="nav-item">
            <%= link_to home_about_path, class: 'nav-link text-light' do %>
              <i class="fas fa-link"></i> About
            <% end %>
          </li>
          <li class="nav-item">
            <%= link_to new_user_registration_path, class: 'nav-link text-light' do %>
              <i class="fas fa-user-plus"></i> Sign up
            <% end %>
          </li>
          <li class="nav-item">
            <%= link_to new_user_session_path, class: 'nav-link text-light' do %>
              <i class="fas fa-sign-in-alt"></i> Log in
            <% end %>
          </li>
          <% end %>
        </ul>
      </div>
    </nav>
  </header>
  <p><%= notice %></p>
  <%= yield %>
  <footer>
    <div class="container mt-5">
      <div class="row">
        <div class="mx-auto">
          <p>CopyRight Infratop.inc</p>
        </div>
      </div>
    </div>
  </footer>
</body>
</html>

app/views/users/edit.html.erb
<main>
  <p id="notice"></p>
  <div class="container">
    <div class="row">
      <div class="col-sm-12 col-md-8 col-lg-5 px-5 px-sm-0 mx-auto">
        <h2>User info</h2>
        <%= form_with model: @user do |f| %>
        
          <% if @user.errors.any? %>
            <div id="error_explanation">
              <h3><%= pluralize(@user.errors.count, "error") %> prohibited this obj from being saved:</h3>
              <ul>
              <% @user.errors.full_messages.each do |message| %>
                <li><%= message %></li>
              <% end %>
              </ul>
            </div>
          <% end %>
          
        <div class="form-group">
          <label for="inputName">Name</label><br>
          <%= f.text_field :name, autofocus: true, id:"inputName", placeholder: "名前", style: "width: 480px;" %><br>
        </div>
        <div class="form-group">
          <label for="inputImage">Image</label><br>
          <%= f.file_field :profile_image, placeholder: "image", accept: "image/*" %>
        </div>
        <div class="form-group">
          <label for="introduction"%>Introduction</label><br>
          <%= f.text_area :introduction, id: "introduction", style: "width: 480px;" %>
        </div>
        <%= f.submit "Update User", class: "btn btn-secondary" %>
        <% end %>

      </div>
    </div>
  </div>
</main>

app/views/users/index.html.erb
<main>
  <p id="notice"></p>
  <div class="container px-5 px-sm-0" >
    <div class="row">
      <%= render "books/user_info", user: @user, book: @book %>

      <div class="col-md-8 offset-md-1">
        <h2>Users</h2>
          <table class="table table-hover">
            <thead>
              <tr>
                <th>image</th>
                <th>name</th>
                <th></th>
                <th colspan="3"></th>
              </tr>
            </thead>
            <tbody>
              <% @users.each do |user| %>
            <tr>
              <td><%= image_tag user.get_profile_image(100,100) %></td>
              <td><%= user.name %></td>
              <td><%= link_to 'Show', user_path(user) %></td>
            </tr>
              <% end %>
            </tbody>
        </table>
    </div>
  </div>
</main>

app/views/users/show.html.erb
<main>
  <p id="notice"></p>
  <div class="container px-5 px-sm-0" >
    <div class="row">
      <%= render "books/user_info", user: @user, book: @book_new %>

        <div class="col-md-8 offset-md-1">
        <h2>Books</h2>
          <table class="table table-hover">
            <thead>
              <tr>
                <th></th>
                <th>Title</th>
                <th>Opinion</th>
                <th colspan="3"></th>
              </tr>
            </thead>
            <tbody>
            <% @user_books.each do |book| %>
            <tr>
              <td>
                <%= link_to image_tag(@user.get_profile_image(100,100)), user_path(@user) %><br>
              </td>
              <td><%= link_to book.title, book_path(book) %></td>
              <td><%= book.body %></td>
            </tr>
            <% end %>
            </tbody>
        </table>
      </div>
    </div>
  </div>
</main>